Tracer",
Junkrat",
Brigitte",
Orisa",
Zarya",
Doomfist",
Baptiste",
Bastion",
Roadhog
D.Va
Wrecking Ball
Mercy
Ana
Winston
Sigma
Lucio
Moira
Hanzo
Reinhardt
Pharah
Sombra
Ashe
Reaper
Widowmaker
Mei
Soldier: 76
Zenyatta
McCree
Genji
Torbjorn
Symmetra
Echo